# -*- coding: utf-8 -*-
"""Tareas1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D1TTaWsynArxKuILGf2XuYhNu3Hf7t6g

Básicos
"""

#input() esta funciónuncorporada en pythonse utiliza para recolectar información
edad= int(input("¿Cuantos años tienes"))
años_hasta_cien=100-edad
print("Te faltan"+ str(años_hasta_cien))

a = float(input("Introduce tu primer número: ") )
b= float(input("Introduce tu segundo número: ") )
opcion = 0 #Para poder decir si es suma,resta,multiplicación
print("""
    ¿Que número  quieres hacer?
    1) Sumar
    2) Restar
    3) Multiplica
    4) Dividir
    """)

opcion = int(input("Elige una opción: ") )

if opcion == 1:
  print("RESULTADO: La suma de",a,"+",b,"es igual a",a+b)
elif opcion == 2:
    print("RESULTADO: La resta de",a,"-",b,"es igual a",a-b)
elif opcion == 3:
    print("RESULTADO: El producto de",a,"*",b,"es igual a",a*b)
elif opcion == 4:
    print("RESULTADO: La Divición de",a,"*",b,"es igual a",a/b)
else:
    print("Opción incorrecta")

#Tarifas de cine
#Un cine cobra diferentes tarifas de entrada según, la edad de la persona si la persona es menor de 3 años entrada gratis
#Si tiene 3 y 12 años cuesta 10
#si tiene más de 12, la entrada cuesta 15
#Que el programa pida la edad y que imprima cuanto tiene que pagar
a = int(input("Introduce tu edad: ") )
if a<3:
  print("RESULTADO: Lo que tienes que pagar, debido a tu edad es<=",3," es de",0)
elif a >= 3 and a<12:
  print("RESULTADO: Lo que tienes que pagar, por que tu edad es de > 3 y < 12  es de",10)
else:
  print("RESULTADO: Lo que tienes que pagar, por que tu edad es> 12 es de",15)

#Escribe un programa que pida al usuario un año y luego imprima si ese año es bisiesto a no, recuerda que un año bisiesto es divicible
#por 4 pero no es divicible por 100 a menos quesea divicible entre 400
a = int(input("Introduce tu año: ") )
if a % 4 ==0 and (a % 100!=0 or a % 400==0 ): #% es para poder decir la cantidad restante de una divición lo que es MOD en excel o Power bi
  print("Es Bisiesto")
else:
  print("No es Bisiesto")

#Has una lista que te regrese los numeros primos del 1 al 100000 ejemplo1
i=1
for i in range(100000):
  if i%2 !=0:
    print(i)