# -*- coding: utf-8 -*-
"""Probabilidad

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11LHTDA-e28_VCPDCnXqdtw7Dc7-bN0cq
"""

import numpy as np

#probabilidad clasica = num_exitos/n_simulaciones(total)

bola_roja=15
bola_azul=7
contador=1
"probalilidad primera tirada bola roja"
print("Bola roja",bola_roja/(bola_azul+bola_roja))
#Probabilidad segunda tirada sea roja si se deja fuera la primera bola
bola_roja-=1
probabilidad_roja_segundo=bola_roja/(bola_azul+bola_roja)
print(probabilidad_roja_segundo)